version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: tic-tac-toe-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: tic-tac-toe-php-fpm
      working_dir: /application
      user: 'root:1000'
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
